// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpHE6CEscbsZB2-J7Pgdnl0PsvahWDjVo',
    appId: '1:288927703186:web:2aa6c1e9a5e3e5014c464b',
    messagingSenderId: '288927703186',
    projectId: 'akdeniz-cep-36d3f',
    authDomain: 'akdeniz-cep-36d3f.firebaseapp.com',
    storageBucket: 'akdeniz-cep-36d3f.firebasestorage.app',
    measurementId: 'G-YNX3KGEW8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR7-eOElsvDh2gKCR2Vt_RRwo38K147jE',
    appId: '1:288927703186:android:ee431f40b3d5da684c464b',
    messagingSenderId: '288927703186',
    projectId: 'akdeniz-cep-36d3f',
    storageBucket: 'akdeniz-cep-36d3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXG8AoCFEUy5nIvvTh-ZSc2IqZ9-JapTs',
    appId: '1:288927703186:ios:af3cd491a468568e4c464b',
    messagingSenderId: '288927703186',
    projectId: 'akdeniz-cep-36d3f',
    storageBucket: 'akdeniz-cep-36d3f.firebasestorage.app',
    iosBundleId: 'com.akdenizcep.akdenizcep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXG8AoCFEUy5nIvvTh-ZSc2IqZ9-JapTs',
    appId: '1:288927703186:ios:af3cd491a468568e4c464b',
    messagingSenderId: '288927703186',
    projectId: 'akdeniz-cep-36d3f',
    storageBucket: 'akdeniz-cep-36d3f.firebasestorage.app',
    iosBundleId: 'com.akdenizcep.akdenizcep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpHE6CEscbsZB2-J7Pgdnl0PsvahWDjVo',
    appId: '1:288927703186:web:2a8cd3a813201cc14c464b',
    messagingSenderId: '288927703186',
    projectId: 'akdeniz-cep-36d3f',
    authDomain: 'akdeniz-cep-36d3f.firebaseapp.com',
    storageBucket: 'akdeniz-cep-36d3f.firebasestorage.app',
    measurementId: 'G-3H6ZX2DKVD',
  );
}
